env:
  CARGO_TERM_COLOR: always

task:
  name: Build macOS ARM64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:sonoma
  env:
    PATH: "$PATH:$HOME/.cargo/bin"
  setup_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
    - source ~/.nvm/nvm.sh && nvm install 20
  build_script:
    - cd web
    - source ~/.nvm/nvm.sh && npm ci
    - source ~/.nvm/nvm.sh && npm run build
    - cargo install tauri-cli --version "^2.0"
    - cargo tauri build --target aarch64-apple-darwin --bundles dmg
  artifacts:
    path: "web/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg"

windows_task:
  name: Build Windows
  windows_container:
    image: cirrusci/windowsservercore:visualstudio2022
  env:
    PATH: "$PATH;$HOME\.cargo\bin;C:\Program Files\nodejs;C:\Program Files\Git\bin"
  setup_script:
    - curl -sSf https://win.rustup.rs/x86_64 -o rustup-init.exe
    - rustup-init.exe -y --default-toolchain stable
    - refreshenv
    - npm install -g npm@20
  build_script:
    - cd web
    - npm ci
    - npm run build
    - cargo install tauri-cli --version "^2.0"
    - cargo tauri build --bundles msi
  artifacts:
    path: "web/src-tauri/target/release/bundle/msi/*.msi"

linux_task:
  name: Build Linux
  container:
    image: ubuntu:22.04
  setup_script:
    - apt-get update
    - apt-get install -y curl nodejs npm cargo rustc libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
  build_script:
    - cd web
    - npm ci
    - npm run build
    - cargo install tauri-cli --version "^2.0"
    - cargo tauri build --bundles deb,appimage
  artifacts:
    path: "web/src-tauri/target/release/bundle/*/*.{deb,AppImage}"
