//! Auto-authentication: read API key from local redb database.
//!
//! When `NEOMIND_API_KEY` env var is not set, the CLI can automatically
//! read the default API key from the local `api_keys.redb`. The data directory
//! is located via [`resolve_data_dir`] (cross-platform, CWD-independent). This
//! requires:
//! 1. The API server to have been started at least once (creates the DB)
//! 2. The `encryption_key` file to exist (auto-generated by server)
//!
//! This is the primary auth mechanism for SSH terminal users — no manual
//! key configuration needed.

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use base64::Engine;
use redb::{Database, ReadableTable, TableDefinition};
use tracing::{debug, warn};

const API_KEYS_TABLE: TableDefinition<&str, &[u8]> = TableDefinition::new("api_keys");
const API_KEY_HASHES_TABLE: TableDefinition<&str, &[u8]> = TableDefinition::new("api_key_hashes");

/// Minimal ApiKeyInfo for deserialization (matches neomind-api auth.rs).
#[derive(serde::Deserialize)]
struct ApiKeyInfo {
    #[allow(dead_code)]
    id: String,
    #[allow(dead_code)]
    name: String,
    #[allow(dead_code)]
    created_at: i64,
    permissions: Vec<String>,
    active: bool,
}

/// Resolve the CLI config directory for storing credentials.
///
/// Priority:
/// 1. `NEOMIND_CONFIG_DIR` environment variable (explicit override)
/// 2. Platform default (`dirs::config_dir()/neomind`)
///
/// Returns `None` only if the platform has no config dir (extremely rare).
pub fn resolve_cli_config_dir() -> Option<std::path::PathBuf> {
    // 1. Explicit override
    if let Ok(dir) = std::env::var("NEOMIND_CONFIG_DIR") {
        if !dir.is_empty() {
            return Some(std::path::PathBuf::from(dir));
        }
    }
    // 2. Platform default
    dirs::config_dir().map(|d| d.join("neomind"))
}

/// Path to the CLI credential file (`{config_dir}/api_key`).
pub fn cli_credential_path() -> Option<std::path::PathBuf> {
    resolve_cli_config_dir().map(|d| d.join("api_key"))
}

/// Read a credential from an explicit path (no env-var lookup).
fn read_credential_from_path(path: &std::path::Path) -> Option<String> {
    let key = std::fs::read_to_string(path).ok()?;
    let key = key.trim();
    if key.is_empty() {
        None
    } else {
        Some(key.to_string())
    }
}

/// Write a credential to an explicit path with 0600 permissions.
fn write_credential_to_path(path: &std::path::Path, key: &str) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            anyhow::anyhow!("Failed to create config directory {}: {}", parent.display(), e)
        })?;
    }
    std::fs::write(path, key).map_err(|e| {
        anyhow::anyhow!("Failed to write credential file {}: {}", path.display(), e)
    })?;
    set_file_mode_0600(path);
    Ok(())
}

/// Read a previously logged-in API key from the credential file.
pub fn read_logged_in_key() -> Option<String> {
    read_credential_from_path(&cli_credential_path()?)
}

/// Write an API key to the credential file with 0600 permissions.
pub fn write_credential(key: &str) -> anyhow::Result<()> {
    let path = cli_credential_path().ok_or_else(|| {
        anyhow::anyhow!(
            "Cannot determine config directory (unsupported platform). \
             Set NEOMIND_CONFIG_DIR env to specify a custom location"
        )
    })?;
    write_credential_to_path(&path, key)
}

/// Remove the credential file (logout).
pub fn remove_credential() -> anyhow::Result<()> {
    if let Some(path) = cli_credential_path() {
        if path.exists() {
            std::fs::remove_file(&path)?;
        }
    }
    Ok(())
}

/// Set file permissions to 0600 (owner read/write only) on Unix.
#[cfg(unix)]
fn set_file_mode_0600(path: &std::path::Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
}

#[cfg(not(unix))]
fn set_file_mode_0600(_path: &std::path::Path) {}

/// Resolve the NeoMind data directory using a cross-platform, CWD-independent
/// lookup. Priority:
///
/// 1. `NEOMIND_DATA_DIR` environment variable (explicit override)
/// 2. Platform user-level default (`dirs::data_local_dir()/neomind`) — only
///    used if it already exists, so we never silently create a stray data dir
/// 3. `./data` (legacy fallback: relative to CWD, for running from install root)
///
/// This lets the CLI auto-authenticate regardless of working directory on
/// macOS / Linux / Windows, without depending on platform keychains (which are
/// unavailable on headless edge devices).
pub fn resolve_data_dir() -> String {
    // 1. Explicit override
    if let Ok(dir) = std::env::var("NEOMIND_DATA_DIR") {
        if !dir.is_empty() {
            return dir;
        }
    }
    // 2. Platform user-level default (only if it already exists)
    if let Some(local) = dirs::data_local_dir() {
        let candidate = local.join("neomind");
        if candidate.is_dir() {
            return candidate.to_string_lossy().into_owned();
        }
    }
    // 3. Legacy fallback (relative to CWD)
    "data".to_string()
}

/// Try to read the default API key.
///
/// Priority:
/// 1. Credential file written by `neomind login` (`{cli_config_dir}/api_key`)
/// 2. redb database via [`resolve_data_dir`] (fallback for pre-login setups)
///
/// Returns `None` if neither source yields a key.
pub fn read_default_api_key() -> Option<String> {
    // 1. Credential file from `neomind login` (explicit, highest local priority)
    if let Some(key) = read_logged_in_key() {
        return Some(key);
    }
    // 2. redb fallback
    read_default_api_key_from(&resolve_data_dir())
}

/// Read default API key from a specific data directory.
pub fn read_default_api_key_from(data_dir: &str) -> Option<String> {
    let enc_key_path = format!("{}/encryption_key", data_dir);
    let db_path = format!("{}/api_keys.redb", data_dir);

    // 1. Read encryption key from file
    let key_hex = std::fs::read_to_string(&enc_key_path)
        .map(|s| s.trim().to_string())
        .ok()?;

    let key_bytes = hex::decode(&key_hex).ok()?;
    if key_bytes.len() < 32 {
        warn!("Encryption key too short in {}", enc_key_path);
        return None;
    }

    // 2. Derive AES-256 key (same as CryptoService::derive_key)
    let mut aes_key = [0u8; 32];
    if key_bytes.len() >= 32 {
        aes_key.copy_from_slice(&key_bytes[..32]);
    }

    // 3. Open redb database
    let db_path_ref = std::path::Path::new(&db_path);
    if !db_path_ref.exists() {
        debug!("API keys database not found at {}", db_path);
        return None;
    }

    let db = Database::open(db_path_ref).ok()?;
    let read_txn = db.begin_read().ok()?;

    // 4. Read encrypted keys
    let table = match read_txn.open_table(API_KEYS_TABLE) {
        Ok(t) => t,
        Err(_) => {
            debug!("api_keys table not found in database");
            return None;
        }
    };

    let hash_table = read_txn.open_table(API_KEY_HASHES_TABLE).ok();

    let cipher = Aes256Gcm::new(&aes_key.into());

    // 5. Find first active key with wildcard permissions
    for item in table.iter().ok()? {
        let (hash_key, value) = item.ok()?;
        let encrypted = String::from_utf8(value.value().to_vec()).ok()?;

        // Decrypt the key
        let plaintext = match decrypt_api_key(&cipher, &encrypted) {
            Some(k) => k,
            None => {
                warn!("Failed to decrypt API key {}", hash_key.value());
                continue;
            }
        };

        // Check metadata for active + wildcard permissions
        if let Some(ref ht) = hash_table {
            if let Ok(Some(info_bytes)) = ht.get(hash_key.value()) {
                if let Ok(info) = bincode::deserialize::<ApiKeyInfo>(info_bytes.value()) {
                    if info.active && info.permissions.contains(&"*".to_string()) {
                        debug!("Auto-auth: using API key '{}' ({})", info.name, info.id);
                        return Some(plaintext);
                    }
                }
            }
        }

        // Fallback: if no metadata, use the first key we can decrypt
        // (covers migration scenario)
        debug!("Auto-auth: using first decryptable API key (no metadata check)");
        return Some(plaintext);
    }

    debug!("No suitable API key found in database");
    None
}

/// Decrypt an API key using AES-256-GCM (matches CryptoService::decrypt).
fn decrypt_api_key(cipher: &Aes256Gcm, encoded: &str) -> Option<String> {
    let combined = base64::engine::general_purpose::STANDARD
        .decode(encoded)
        .ok()?;

    if combined.len() < 12 {
        return None;
    }

    let (nonce_bytes, ciphertext) = combined.split_at(12);
    let nonce = Nonce::from_slice(nonce_bytes);

    let plaintext = cipher.decrypt(nonce, ciphertext).ok()?;
    String::from_utf8(plaintext).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_read_nonexistent_returns_none() {
        let result = read_default_api_key_from("/tmp/neomind-nonexistent-test-data");
        assert!(result.is_none());
    }

    #[test]
    fn test_resolve_data_dir_env_override() {
        // NEOMIND_DATA_DIR takes priority over platform default and legacy "data".
        std::env::set_var("NEOMIND_DATA_DIR", "/tmp/neomind-resolve-test-unique");
        assert_eq!(resolve_data_dir(), "/tmp/neomind-resolve-test-unique");
        std::env::remove_var("NEOMIND_DATA_DIR");
    }

    #[test]
    fn test_resolve_data_dir_empty_env_falls_back() {
        // An empty NEOMIND_DATA_DIR should be ignored (fall through to other sources).
        std::env::set_var("NEOMIND_DATA_DIR", "");
        let resolved = resolve_data_dir();
        // Must not be the empty string — should be either "data" or a platform default.
        assert!(!resolved.is_empty(), "empty env must not yield empty data dir");
        std::env::remove_var("NEOMIND_DATA_DIR");
    }

    #[test]
    fn test_resolve_cli_config_dir_env_override() {
        let tmp = std::env::temp_dir().join(format!(
            "neomind-config-test-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::env::set_var("NEOMIND_CONFIG_DIR", tmp.to_str().unwrap());
        assert_eq!(
            resolve_cli_config_dir(),
            Some(tmp.clone())
        );
        std::env::remove_var("NEOMIND_CONFIG_DIR");
    }

    #[test]
    fn test_credential_write_read_logout_roundtrip() {
        // Use path-based functions to avoid env-var interference with parallel tests.
        let tmp = std::env::temp_dir().join(format!(
            "neomind-cred-roundtrip-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let cred_path = tmp.join("api_key");

        // Initially no key
        assert!(read_credential_from_path(&cred_path).is_none());

        // Write
        write_credential_to_path(&cred_path, "nmk_testkey123456").unwrap();
        assert!(cred_path.exists(), "credential file should exist after write");

        // Unix permission check
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::metadata(&cred_path).unwrap().permissions().mode();
            assert_eq!(
                perms & 0o777,
                0o600,
                "credential file should have 0600 permissions"
            );
        }

        // Read back
        assert_eq!(
            read_credential_from_path(&cred_path),
            Some("nmk_testkey123456".to_string())
        );

        // Logout (remove file)
        std::fs::remove_file(&cred_path).unwrap();
        assert!(!cred_path.exists(), "credential file should be gone after logout");
        assert!(read_credential_from_path(&cred_path).is_none());

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
