//! Auto-authentication: read API key from local redb database.
//!
//! When `NEOMIND_API_KEY` env var is not set, the CLI can automatically
//! read the default API key from `data/api_keys.redb`. This requires:
//! 1. The API server to have been started at least once (creates the DB)
//! 2. The `data/encryption_key` file to exist (auto-generated by server)
//!
//! This is the primary auth mechanism for SSH terminal users — no manual
//! key configuration needed.

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use base64::Engine;
use redb::{Database, ReadableTable, TableDefinition};
use tracing::{debug, warn};

const API_KEYS_TABLE: TableDefinition<&str, &[u8]> = TableDefinition::new("api_keys");
const API_KEY_HASHES_TABLE: TableDefinition<&str, &[u8]> = TableDefinition::new("api_key_hashes");

/// Minimal ApiKeyInfo for deserialization (matches neomind-api auth.rs).
#[derive(serde::Deserialize)]
struct ApiKeyInfo {
    #[allow(dead_code)]
    id: String,
    #[allow(dead_code)]
    name: String,
    #[allow(dead_code)]
    created_at: i64,
    permissions: Vec<String>,
    active: bool,
}

/// Try to read the default API key from the local database.
///
/// Returns `None` if:
/// - The database file doesn't exist
/// - The encryption key file is missing
/// - No active key with wildcard permissions is found
/// - Decryption fails (wrong encryption key)
pub fn read_default_api_key() -> Option<String> {
    read_default_api_key_from("data")
}

/// Read default API key from a specific data directory.
pub fn read_default_api_key_from(data_dir: &str) -> Option<String> {
    let enc_key_path = format!("{}/encryption_key", data_dir);
    let db_path = format!("{}/api_keys.redb", data_dir);

    // 1. Read encryption key from file
    let key_hex = std::fs::read_to_string(&enc_key_path)
        .map(|s| s.trim().to_string())
        .ok()?;

    let key_bytes = hex::decode(&key_hex).ok()?;
    if key_bytes.len() < 32 {
        warn!("Encryption key too short in {}", enc_key_path);
        return None;
    }

    // 2. Derive AES-256 key (same as CryptoService::derive_key)
    let mut aes_key = [0u8; 32];
    if key_bytes.len() >= 32 {
        aes_key.copy_from_slice(&key_bytes[..32]);
    }

    // 3. Open redb database
    let db_path_ref = std::path::Path::new(&db_path);
    if !db_path_ref.exists() {
        debug!("API keys database not found at {}", db_path);
        return None;
    }

    let db = Database::open(db_path_ref).ok()?;
    let read_txn = db.begin_read().ok()?;

    // 4. Read encrypted keys
    let table = match read_txn.open_table(API_KEYS_TABLE) {
        Ok(t) => t,
        Err(_) => {
            debug!("api_keys table not found in database");
            return None;
        }
    };

    let hash_table = read_txn.open_table(API_KEY_HASHES_TABLE).ok();

    let cipher = Aes256Gcm::new(&aes_key.into());

    // 5. Find first active key with wildcard permissions
    for item in table.iter().ok()? {
        let (hash_key, value) = item.ok()?;
        let encrypted = String::from_utf8(value.value().to_vec()).ok()?;

        // Decrypt the key
        let plaintext = match decrypt_api_key(&cipher, &encrypted) {
            Some(k) => k,
            None => {
                warn!("Failed to decrypt API key {}", hash_key.value());
                continue;
            }
        };

        // Check metadata for active + wildcard permissions
        if let Some(ref ht) = hash_table {
            if let Ok(Some(info_bytes)) = ht.get(hash_key.value()) {
                if let Ok(info) = bincode::deserialize::<ApiKeyInfo>(info_bytes.value()) {
                    if info.active && info.permissions.contains(&"*".to_string()) {
                        debug!("Auto-auth: using API key '{}' ({})", info.name, info.id);
                        return Some(plaintext);
                    }
                }
            }
        }

        // Fallback: if no metadata, use the first key we can decrypt
        // (covers migration scenario)
        debug!("Auto-auth: using first decryptable API key (no metadata check)");
        return Some(plaintext);
    }

    debug!("No suitable API key found in database");
    None
}

/// Decrypt an API key using AES-256-GCM (matches CryptoService::decrypt).
fn decrypt_api_key(cipher: &Aes256Gcm, encoded: &str) -> Option<String> {
    let combined = base64::engine::general_purpose::STANDARD
        .decode(encoded)
        .ok()?;

    if combined.len() < 12 {
        return None;
    }

    let (nonce_bytes, ciphertext) = combined.split_at(12);
    let nonce = Nonce::from_slice(nonce_bytes);

    let plaintext = cipher.decrypt(nonce, ciphertext).ok()?;
    String::from_utf8(plaintext).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_read_nonexistent_returns_none() {
        let result = read_default_api_key_from("/tmp/neomind-nonexistent-test-data");
        assert!(result.is_none());
    }
}
