//! IPC (Inter-Process Communication) protocol for isolated extensions
//!
//! This module defines the message protocol used for communication between
//! the main NeoMind process and isolated extension processes.

use serde::{Deserialize, Serialize};

/// IPC message sent from host to extension process
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum IpcMessage {
    /// Initialize extension with config
    Init {
        /// Configuration JSON
        config: serde_json::Value,
    },

    /// Execute a command
    ExecuteCommand {
        /// Command name
        command: String,
        /// Command arguments
        args: serde_json::Value,
        /// Request ID for tracking
        request_id: u64,
    },

    /// Get metrics
    ProduceMetrics {
        /// Request ID for tracking
        request_id: u64,
    },

    /// Health check
    HealthCheck {
        /// Request ID for tracking
        request_id: u64,
    },

    /// Get metadata
    GetMetadata {
        /// Request ID for tracking
        request_id: u64,
    },

    /// Get event subscriptions
    GetEventSubscriptions {
        /// Request ID for tracking
        request_id: u64,
    },

    /// Get extension statistics (start_count, stop_count, error_count, etc.)
    GetStats {
        /// Request ID for tracking
        request_id: u64,
    },

    /// Graceful shutdown
    Shutdown,

    /// Ping (keep-alive)
    Ping {
        /// Timestamp
        timestamp: i64,
    },

    // =========================================================================
    // Streaming Support (Push Mode)
    // =========================================================================

    /// Initialize a stream session (Push/Stateful mode)
    InitStreamSession {
        /// Session ID (generated by host)
        session_id: String,
        /// Extension ID
        extension_id: String,
        /// Session configuration
        config: serde_json::Value,
        /// Client info
        client_info: StreamClientInfo,
    },

    /// Close a stream session
    CloseStreamSession {
        /// Session ID
        session_id: String,
    },

    /// Process a data chunk in a session
    ProcessStreamChunk {
        /// Request ID for tracking response
        request_id: u64,
        /// Session ID
        session_id: String,
        /// Chunk data
        chunk: StreamDataChunk,
    },

    /// Get stream capability
    GetStreamCapability {
        /// Request ID for tracking
        request_id: u64,
    },

    // =========================================================================
    // Stateless Mode Support
    // =========================================================================

    /// Process a single data chunk (stateless mode)
    ///
    /// Used for one-shot processing where each request is independent.
    /// Examples: image analysis, single inference, data transformation.
    ProcessChunk {
        /// Request ID for tracking response
        request_id: u64,
        /// Chunk data
        chunk: StreamDataChunk,
    },

    // =========================================================================
    // Push Mode Support
    // =========================================================================

    /// Start pushing data for a session (Push mode)
    ///
    /// Called after InitStreamSession for Push mode extensions.
    /// The extension should start its data production loop and push
    /// outputs via PushOutput messages.
    StartPush {
        /// Request ID for tracking
        request_id: u64,
        /// Session ID
        session_id: String,
    },

    /// Stop pushing data for a session (Push mode)
    ///
    /// Called when the client disconnects or session is closed.
    StopPush {
        /// Request ID for tracking
        request_id: u64,
        /// Session ID
        session_id: String,
    },

    /// Execute multiple commands in a batch
    ExecuteBatch {
        /// Commands to execute
        commands: Vec<super::ipc_batch_types::BatchCommand>,
        /// Request ID for tracking
        request_id: u64,
    },

    // =========================================================================
    // Capability Invocation (for WASM extensions)
    // =========================================================================

    /// Invoke a capability from WASM extension
    ///
    /// This message is sent from the extension-runner to the main process
    /// when a WASM extension calls a capability via host_invoke_capability.
    InvokeCapability {
        /// Request ID for tracking
        request_id: u64,
        /// Capability name (e.g., "device_metrics_read")
        capability: String,
        /// Parameters for the capability
        params: serde_json::Value,
    },

    /// Subscribe to events from WASM extension
    SubscribeEvents {
        /// Request ID for tracking
        request_id: u64,
        /// Event types to subscribe to
        event_types: Vec<String>,
        /// Optional filter
        filter: Option<serde_json::Value>,
    },

    /// Unsubscribe from events
    UnsubscribeEvents {
        /// Request ID for tracking
        request_id: u64,
        /// Subscription ID
        subscription_id: String,
    },

    /// Poll for events
    PollEvents {
        /// Request ID for tracking
        request_id: u64,
        /// Subscription ID
        subscription_id: String,
    },

    /// Event push from host to extension
    /// This is sent by host without a prior request from extension
    EventPush {
        /// Event type
        event_type: String,
        /// Event payload
        payload: serde_json::Value,
        /// Event timestamp
        timestamp: i64,
    },

    /// Capability result from host to extension
    /// This is the response to a CapabilityRequest from the extension
    CapabilityResult {
        /// Request ID (matches the CapabilityRequest)
        request_id: u64,
        /// Result of the capability invocation
        result: serde_json::Value,
        /// Error message if failed
        error: Option<String>,
    },
}

/// Stream client info (for IPC transfer)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamClientInfo {
    pub client_id: String,
    pub ip_addr: Option<String>,
    pub user_agent: Option<String>,
}

/// Stream data chunk (for IPC transfer)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamDataChunk {
    pub sequence: u64,
    pub data_type: String,
    pub data: Vec<u8>,
    pub timestamp: i64,
    pub is_last: bool,
}

/// IPC response sent from extension process to host
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum IpcResponse {
    /// Extension is ready with its full descriptor
    Ready {
        /// Complete extension descriptor (metadata, commands, metrics)
        descriptor: super::super::system::ExtensionDescriptor,
    },

    /// Command execution success
    Success {
        /// Request ID
        request_id: u64,
        /// Result data
        data: serde_json::Value,
    },

    /// Error response
    Error {
        /// Request ID (0 if not applicable)
        request_id: u64,
        /// Error message
        error: String,
        /// Error kind
        kind: ErrorKind,
    },

    /// Metrics response
    Metrics {
        /// Request ID
        request_id: u64,
        /// Metric values
        metrics: Vec<super::super::system::ExtensionMetricValue>,
    },

    /// Health check response
    Health {
        /// Request ID
        request_id: u64,
        /// Is healthy
        healthy: bool,
    },

    /// Metadata response
    Metadata {
        /// Request ID
        request_id: u64,
        /// Extension metadata
        metadata: super::super::system::ExtensionMetadata,
    },

    /// Event subscriptions response
    EventSubscriptions {
        /// Request ID
        request_id: u64,
        /// Event types the extension subscribes to
        event_types: Vec<String>,
    },

    /// Statistics response
    Stats {
        /// Request ID
        request_id: u64,
        /// Number of times the extension has been started
        start_count: u64,
        /// Number of times the extension has been stopped
        stop_count: u64,
        /// Number of errors encountered
        error_count: u64,
        /// Last error message
        last_error: Option<String>,
    },

    /// Pong response
    Pong {
        /// Original timestamp
        timestamp: i64,
    },

    // =========================================================================
    // Streaming Support (Push Mode)
    // =========================================================================

    /// Stream session initialized
    StreamSessionInit {
        /// Session ID
        session_id: String,
        /// Success status
        success: bool,
        /// Error message if failed
        error: Option<String>,
    },

    /// Stream session closed
    StreamSessionClosed {
        /// Session ID
        session_id: String,
        /// Total frames processed
        total_frames: u64,
        /// Duration in milliseconds
        duration_ms: u64,
    },

    /// Stream chunk processed result
    StreamChunkResult {
        /// Request ID
        request_id: u64,
        /// Session ID
        session_id: String,
        /// Input sequence
        input_sequence: u64,
        /// Output sequence
        output_sequence: u64,
        /// Result data
        data: Vec<u8>,
        /// Data type MIME
        data_type: String,
        /// Processing time in ms
        processing_ms: f32,
    },

    /// Stream capability response
    StreamCapability {
        /// Request ID
        request_id: u64,
        /// Capability JSON (StreamCapability serialized)
        capability: Option<serde_json::Value>,
    },

    // =========================================================================
    // Stateless Mode Response
    // =========================================================================

    /// Stateless chunk processing result
    ChunkResult {
        /// Request ID
        request_id: u64,
        /// Input sequence
        input_sequence: u64,
        /// Output sequence
        output_sequence: u64,
        /// Result data
        data: Vec<u8>,
        /// Data type MIME
        data_type: String,
        /// Processing time in ms
        processing_ms: f32,
        /// Optional metadata
        metadata: Option<serde_json::Value>,
    },

    // =========================================================================
    // Push Mode Response
    // =========================================================================

    /// Push mode started
    PushStarted {
        /// Request ID
        request_id: u64,
        /// Session ID
        session_id: String,
        /// Success status
        success: bool,
        /// Error message if failed
        error: Option<String>,
    },

    /// Push mode stopped
    PushStopped {
        /// Request ID
        request_id: u64,
        /// Session ID
        session_id: String,
        /// Success status
        success: bool,
    },

    // =========================================================================
    // Push Mode - Extension-initiated messages
    // =========================================================================

    /// Extension pushes output data to host (Push mode)
    /// This is sent by extension without a prior request from host
    PushOutput {
        /// Session ID
        session_id: String,
        /// Output sequence
        sequence: u64,
        /// Data
        data: Vec<u8>,
        /// Data type MIME
        data_type: String,
        /// Timestamp
        timestamp: i64,
        /// Optional metadata
        metadata: Option<serde_json::Value>,
    },

    /// Extension reports stream error
    StreamError {
        /// Session ID
        session_id: String,
        /// Error code
        code: String,
        /// Error message
        message: String,
    },

    /// Batch execution results
    BatchResults {
        /// Request ID
        request_id: u64,
        /// Individual command results
        results: Vec<super::ipc_batch_types::BatchResult>,
        /// Total execution time in milliseconds
        total_elapsed_ms: f64,
    },

    // =========================================================================
    // Capability Invocation Responses (for WASM extensions)
    // =========================================================================

    /// Capability invocation result
    CapabilityResult {
        /// Request ID
        request_id: u64,
        /// Result data
        result: serde_json::Value,
        /// Error message if failed
        error: Option<String>,
    },

    /// Event subscription result
    EventSubscriptionResult {
        /// Request ID
        request_id: u64,
        /// Subscription ID if successful
        subscription_id: Option<String>,
        /// Error message if failed
        error: Option<String>,
    },

    /// Event poll result
    EventPollResult {
        /// Request ID
        request_id: u64,
        /// Events received
        events: Vec<serde_json::Value>,
    },

    // =========================================================================
    // Capability Request from Extension (bidirectional)
    // =========================================================================

    /// Capability request from extension to host
    /// This allows isolated extensions to call host capabilities
    CapabilityRequest {
        /// Request ID for tracking
        request_id: u64,
        /// Capability name (e.g., "device_metrics_read")
        capability: String,
        /// Parameters for the capability
        params: serde_json::Value,
    },
}

/// Push output data (extracted from PushOutput response)
/// Used for forwarding push data to WebSocket clients
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PushOutputData {
    /// Session ID
    pub session_id: String,
    /// Output sequence
    pub sequence: u64,
    /// Data
    pub data: Vec<u8>,
    /// Data type MIME
    pub data_type: String,
    /// Timestamp
    pub timestamp: i64,
    /// Optional metadata
    pub metadata: Option<serde_json::Value>,
}

impl From<IpcResponse> for Option<PushOutputData> {
    fn from(response: IpcResponse) -> Self {
        match response {
            IpcResponse::PushOutput {
                session_id,
                sequence,
                data,
                data_type,
                timestamp,
                metadata,
            } => Some(PushOutputData {
                session_id,
                sequence,
                data,
                data_type,
                timestamp,
                metadata,
            }),
            _ => None,
        }
    }
}

/// Error kind classification
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ErrorKind {
    /// Command not found
    CommandNotFound,
    /// Invalid arguments
    InvalidArguments,
    /// Execution failed
    ExecutionFailed,
    /// Timeout
    Timeout,
    /// Not found
    NotFound,
    /// Invalid format
    InvalidFormat,
    /// Not initialized
    NotInitialized,
    /// Internal error
    Internal,
    /// Security error
    Security,
}

impl From<super::super::ExtensionError> for ErrorKind {
    fn from(error: super::super::ExtensionError) -> Self {
        use super::super::ExtensionError;
        match error {
            ExtensionError::CommandNotFound(_) => ErrorKind::CommandNotFound,
            ExtensionError::InvalidArguments(_) => ErrorKind::InvalidArguments,
            ExtensionError::ExecutionFailed(_) => ErrorKind::ExecutionFailed,
            ExtensionError::Timeout(_) => ErrorKind::Timeout,
            ExtensionError::NotFound(_) => ErrorKind::NotFound,
            ExtensionError::InvalidFormat(_) => ErrorKind::InvalidFormat,
            ExtensionError::MetricNotFound(_) => ErrorKind::NotFound,
            ExtensionError::LoadFailed(_) => ErrorKind::Internal,
            ExtensionError::SecurityError(_) => ErrorKind::Security,
            ExtensionError::SymbolNotFound(_) => ErrorKind::Internal,
            ExtensionError::IncompatibleVersion { .. } => ErrorKind::Internal,
            ExtensionError::NullPointer => ErrorKind::Internal,
            ExtensionError::AlreadyRegistered(_) => ErrorKind::Internal,
            ExtensionError::NotSupported(_) => ErrorKind::Internal,
            ExtensionError::InvalidStreamData(_) => ErrorKind::InvalidFormat,
            ExtensionError::SessionNotFound(_) => ErrorKind::NotFound,
            ExtensionError::SessionAlreadyExists(_) => ErrorKind::Internal,
            ExtensionError::InferenceFailed(_) => ErrorKind::ExecutionFailed,
            ExtensionError::Io(_) => ErrorKind::Internal,
            ExtensionError::Json(_) => ErrorKind::InvalidFormat,
            ExtensionError::Other(_) => ErrorKind::Internal,
        }
    }
}

impl IpcMessage {
    /// Serialize message to JSON bytes
    pub fn to_bytes(&self) -> serde_json::Result<Vec<u8>> {
        serde_json::to_vec(self)
    }

    /// Deserialize message from JSON bytes
    pub fn from_bytes(bytes: &[u8]) -> serde_json::Result<Self> {
        serde_json::from_slice(bytes)
    }
}

impl IpcResponse {
    /// Serialize response to JSON bytes
    pub fn to_bytes(&self) -> serde_json::Result<Vec<u8>> {
        serde_json::to_vec(self)
    }

    /// Deserialize response from JSON bytes
    pub fn from_bytes(bytes: &[u8]) -> serde_json::Result<Self> {
        serde_json::from_slice(bytes)
    }

    /// Check if this response is an error
    pub fn is_error(&self) -> bool {
        matches!(self, Self::Error { .. })
    }

    /// Check if this is a Push output (extension-initiated)
    pub fn is_push_output(&self) -> bool {
        matches!(self, Self::PushOutput { .. })
    }

    /// Check if this is a stream error
    pub fn is_stream_error(&self) -> bool {
        matches!(self, Self::StreamError { .. })
    }

    /// Check if this is a capability request from extension
    pub fn is_capability_request(&self) -> bool {
        matches!(self, Self::CapabilityRequest { .. })
    }

    /// Get request ID if applicable
    pub fn request_id(&self) -> Option<u64> {
        match self {
            Self::Ready { .. } => None,
            Self::Success { request_id, .. } => Some(*request_id),
            Self::Error { request_id, .. } => Some(*request_id),
            Self::Metrics { request_id, .. } => Some(*request_id),
            Self::Health { request_id, .. } => Some(*request_id),
            Self::Metadata { request_id, .. } => Some(*request_id),
            Self::EventSubscriptions { request_id, .. } => Some(*request_id),
            Self::Pong { .. } => None,
            Self::StreamSessionInit { .. } => None,
            Self::StreamSessionClosed { .. } => None,
            Self::StreamChunkResult { request_id, .. } => Some(*request_id),
            Self::StreamCapability { request_id, .. } => Some(*request_id),
            Self::ChunkResult { request_id, .. } => Some(*request_id),
            Self::PushStarted { request_id, .. } => Some(*request_id),
            Self::PushStopped { request_id, .. } => Some(*request_id),
            Self::PushOutput { .. } => None,
            Self::StreamError { .. } => None,
            Self::BatchResults { request_id, .. } => Some(*request_id),
            Self::Stats { request_id, .. } => Some(*request_id),
            Self::CapabilityResult { request_id, .. } => Some(*request_id),
            Self::EventSubscriptionResult { request_id, .. } => Some(*request_id),
            Self::EventPollResult { request_id, .. } => Some(*request_id),
            Self::CapabilityRequest { request_id, .. } => Some(*request_id),
        }
    }
}

/// Frame format for IPC communication
///
/// Frame format:
/// - 4 bytes: length (little-endian u32)
/// - N bytes: JSON payload
#[derive(Debug, Clone)]
pub struct IpcFrame {
    /// Payload bytes
    pub payload: Vec<u8>,
}

impl IpcFrame {
    /// Create a new frame from payload
    pub fn new(payload: Vec<u8>) -> Self {
        Self { payload }
    }

    /// Encode frame to bytes (length prefix + payload)
    pub fn encode(&self) -> Vec<u8> {
        let len = self.payload.len() as u32;
        let mut bytes = Vec::with_capacity(4 + self.payload.len());
        bytes.extend_from_slice(&len.to_le_bytes());
        bytes.extend_from_slice(&self.payload);
        bytes
    }

    /// Decode frame from bytes
    /// Returns (frame, remaining_bytes) or error message
    pub fn decode(bytes: &[u8]) -> Result<(Self, usize), &'static str> {
        if bytes.len() < 4 {
            return Err("Not enough bytes for length prefix");
        }

        let len = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]) as usize;

        if bytes.len() < 4 + len {
            return Err("Not enough bytes for payload");
        }

        let payload = bytes[4..4 + len].to_vec();
        Ok((Self { payload }, 4 + len))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_serialization() {
        let msg = IpcMessage::ExecuteCommand {
            command: "test".to_string(),
            args: serde_json::json!({"arg": 1}),
            request_id: 1,
        };

        let bytes = msg.to_bytes().unwrap();
        let decoded = IpcMessage::from_bytes(&bytes).unwrap();

        match decoded {
            IpcMessage::ExecuteCommand { command, args, request_id } => {
                assert_eq!(command, "test");
                assert_eq!(request_id, 1);
                assert_eq!(args, serde_json::json!({"arg": 1}));
            }
            _ => panic!("Wrong message type"),
        }
    }

    #[test]
    fn test_frame_encoding() {
        let payload = b"hello world";
        let frame = IpcFrame::new(payload.to_vec());
        let encoded = frame.encode();

        assert_eq!(encoded.len(), 4 + payload.len());
        assert_eq!(&encoded[0..4], &(payload.len() as u32).to_le_bytes());
        assert_eq!(&encoded[4..], payload);

        let (decoded, consumed) = IpcFrame::decode(&encoded).unwrap();
        assert_eq!(consumed, encoded.len());
        assert_eq!(decoded.payload, payload);
    }
}
